### ISSUE TITLE
Managing sudo/non-sudo

### ISSUE THREAD

**Issue by jpdesigndev** [weareinteractive/ansible-pm2#11]
First off, thank you for an awesome project. It's really helpful.

***

How are you managing switching between root and non-root? For example, to install an NPM package globally (without jumping through hoops) you must be root, but it's not recommended that anyone run a node app under root.

Should I just jump through the hoops of installing pm2 as non-root? Other ideas?

**Comment by franklinkim** [comment]
hi, have to admit, been quite a while since I actually used this role myself and when I was using it, it was in an isolated way, so that I didn't had to worry about running everything as root.

Think a solution might be:
* optionally let the role create a pm2 user
* use `remote_user: "{{ pm2_user }}"` in the manage tasks

**Comment by franklinkim** [comment]
Closing this for now since there is no feedback.
